[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Proxy client requests to functions under /api/*
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
